# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - name: rsync deployments
      uses: burnett01/rsync-deployments@7.0.1
      with:
        switches: -a --delete
        path: dist/
        remote_path: /etc/twitch-discord-bot/
        remote_host: 159.223.213.54
        remote_user: root
        remote_key: ${{ secrets.DEPLOY_KEY }}
